use std::{fs, path::Path};

use folderbase_core::{
    CaptureEntryKind, CaptureExclusionKind, CaptureExclusionReason, CapturePlanLimitKind,
    FolderbaseCaptureError, FolderbaseVersionStore, MAX_CAPTURE_PLAN_RECORDS,
    attest_folderbase_root,
};
use tempfile::{TempDir, tempdir};

const FOLDERBASE_ID: &str = "folderbase_019f9b75-4f42-7f65-a012-2bfecdd8c473";
const MANIFEST: &[u8] = br#"{
  "protocol_version": "0.4.0",
  "folderbase": {
    "id": "folderbase_019f9b75-4f42-7f65-a012-2bfecdd8c473"
  }
}
"#;

fn folderbase() -> TempDir {
    let root = tempdir().expect("temporary Folderbase");
    fs::create_dir(root.path().join(".folderbase")).expect("state directory");
    fs::write(root.path().join(".folderbase/manifest.json"), MANIFEST).expect("manifest");
    fs::write(root.path().join(".folderbaseignore"), "").expect("ignore policy");
    fs::write(root.path().join("FOLDERBASE.md"), "# Folderbase\n").expect("entry");
    root
}

fn entry_paths(plan: &folderbase_core::CapturePlan) -> Vec<(&str, CaptureEntryKind, Option<u64>)> {
    plan.entries()
        .iter()
        .map(|entry| (entry.path(), entry.kind(), entry.bytes()))
        .collect()
}

#[test]
fn open_and_plan_bind_metadata_to_one_attested_root_without_writing() {
    let root = folderbase();
    fs::create_dir(root.path().join("docs")).expect("docs");
    fs::write(root.path().join("docs/notes.md"), "ordinary content\n").expect("notes");
    let state_before = state_paths(root.path());

    let store = FolderbaseVersionStore::open(root.path()).expect("open exact Folderbase");
    let plan = store.plan_capture().expect("metadata plan");

    assert_eq!(plan.root(), root.path().canonicalize().unwrap());
    assert_eq!(plan.folderbase_id(), FOLDERBASE_ID);
    assert_eq!(plan.root_instance_sha256().len(), 64);
    assert_eq!(plan.current_local_head(), None);
    assert_eq!(plan.ignore_policy_sha256().len(), 64);
    assert_eq!(
        entry_paths(&plan),
        vec![
            (".folderbaseignore", CaptureEntryKind::RegularFile, Some(0)),
            ("FOLDERBASE.md", CaptureEntryKind::RegularFile, Some(13)),
            ("docs", CaptureEntryKind::Directory, None),
            ("docs/notes.md", CaptureEntryKind::RegularFile, Some(17)),
        ]
    );
    assert_eq!(plan.exclusions().len(), 0);
    assert_eq!(plan.ignored_paths().len(), 0);
    assert_eq!(state_paths(root.path()), state_before);
}

#[test]
fn ordered_ignore_policy_applies_defaults_negation_required_overrides_and_prunes_directories() {
    let root = folderbase();
    fs::write(
        root.path().join(".folderbaseignore"),
        include_str!("fixtures/capture/ordered.folderbaseignore"),
    )
    .expect("ordered policy");
    fs::write(root.path().join("drop.tmp"), "ignored").expect("temporary file");
    fs::write(root.path().join("keep.tmp"), "included").expect("negated temporary");
    fs::write(root.path().join("important.log"), "last rule wins").expect("ordered file");
    fs::create_dir_all(root.path().join("node_modules/pkg")).expect("reincluded generated tree");
    fs::write(
        root.path().join("node_modules/pkg/index.js"),
        "opaque generated bytes",
    )
    .expect("reincluded generated file");
    fs::create_dir_all(root.path().join("dist/deep")).expect("default excluded directory");

    #[cfg(unix)]
    {
        fs::write(root.path().join("dist/deep/CON"), "must never be visited")
            .expect("nonportable descendant");
    }

    let plan = FolderbaseVersionStore::open(root.path())
        .expect("open")
        .plan_capture()
        .expect("ignored directory is pruned before unsafe descendant traversal");
    let paths = plan
        .entries()
        .iter()
        .map(|entry| entry.path())
        .collect::<Vec<_>>();
    let ignored = plan
        .ignored_paths()
        .iter()
        .map(|entry| entry.path())
        .collect::<Vec<_>>();

    assert!(paths.contains(&".folderbaseignore"));
    assert!(paths.contains(&"FOLDERBASE.md"));
    assert!(paths.contains(&"keep.tmp"));
    assert!(paths.contains(&"node_modules"));
    assert!(paths.contains(&"node_modules/pkg/index.js"));
    assert!(!paths.contains(&"drop.tmp"));
    assert!(!paths.contains(&"important.log"));
    assert!(!paths.iter().any(|path| path.starts_with("dist/")));
    assert_eq!(ignored, vec!["dist", "drop.tmp", "important.log"]);
}

#[test]
fn nested_folderbases_are_typed_boundaries_and_all_regular_file_formats_remain_opaque() {
    let root = folderbase();
    for (path, contents) in [
        ("reference.pdf", b"%PDF opaque".as_slice()),
        ("movie.mov", b"opaque video".as_slice()),
        ("data.csv", b"a,b\n1,2\n".as_slice()),
        ("database.sqlite", b"SQLite format 3\0opaque".as_slice()),
        ("archive.unknown", b"unknown opaque".as_slice()),
        (
            ".git/objects/pack/pack-test.pack",
            b"git pack opaque".as_slice(),
        ),
    ] {
        let path = root.path().join(path);
        fs::create_dir_all(path.parent().unwrap()).expect("opaque parent");
        fs::write(path, contents).expect("opaque regular file");
    }
    let child = root.path().join("Clients/Prosperna");
    fs::create_dir_all(child.join(".folderbase")).expect("nested state");
    fs::write(child.join(".folderbase/manifest.json"), MANIFEST).expect("nested manifest");
    fs::write(child.join("FOLDERBASE.md"), "# Child\n").expect("nested entry");
    fs::write(child.join("CON"), "must not be traversed").expect("unsafe nested descendant");

    let plan = FolderbaseVersionStore::open(root.path())
        .expect("open")
        .plan_capture()
        .expect("plan with opaque boundary");

    for expected in [
        "reference.pdf",
        "movie.mov",
        "data.csv",
        "database.sqlite",
        "archive.unknown",
        ".git/objects/pack/pack-test.pack",
    ] {
        let entry = plan
            .entries()
            .iter()
            .find(|entry| entry.path() == expected)
            .unwrap_or_else(|| panic!("missing opaque regular file {expected}"));
        assert_eq!(entry.kind(), CaptureEntryKind::RegularFile);
        assert!(entry.bytes().is_some());
    }
    assert!(
        !plan
            .entries()
            .iter()
            .any(|entry| entry.path().starts_with("Clients/Prosperna/"))
    );
    let boundary = plan
        .exclusions()
        .iter()
        .find(|exclusion| exclusion.path() == "Clients/Prosperna")
        .expect("typed nested boundary");
    assert_eq!(boundary.kind(), CaptureExclusionKind::NestedFolderbase);
    assert_eq!(
        boundary.reason(),
        CaptureExclusionReason::NestedFolderbaseBoundary
    );
}

#[test]
fn sparse_ten_gibibyte_file_is_planned_by_metadata_and_v1_object_size_is_bounded() {
    let root = folderbase();
    let movie = root.path().join("feature.mov");
    let file = fs::File::create(&movie).expect("sparse movie");
    file.set_len(10 * 1024 * 1024 * 1024)
        .expect("10 GiB sparse length");

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;

        fs::set_permissions(&movie, fs::Permissions::from_mode(0o0))
            .expect("ordinary file contents are unreadable");
    }

    let plan = FolderbaseVersionStore::open(root.path())
        .expect("open")
        .plan_capture()
        .expect("metadata-only planning never opens ordinary bytes");
    let planned = plan
        .entries()
        .iter()
        .find(|entry| entry.path() == "feature.mov")
        .expect("movie metadata");
    assert_eq!(planned.kind(), CaptureEntryKind::RegularFile);
    assert_eq!(planned.bytes(), Some(10 * 1024 * 1024 * 1024));

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;

        fs::set_permissions(&movie, fs::Permissions::from_mode(0o600))
            .expect("restore test cleanup permissions");
    }

    let oversized = root.path().join("too-large.bin");
    let file = fs::File::create(&oversized).expect("oversized sparse file");
    file.set_len(1024 * 1024 * 1024 * 1024 + 1)
        .expect("v1 boundary probe");
    assert!(matches!(
        FolderbaseVersionStore::open(root.path())
            .expect("reopen")
            .plan_capture(),
        Err(FolderbaseCaptureError::InventoryLimitExceeded {
            limit,
            maximum,
            ..
        }) if limit == CapturePlanLimitKind::ObjectBytes
            && maximum == 1024 * 1024 * 1024 * 1024
    ));
}

#[test]
fn plan_is_bound_to_the_current_optional_device_local_head() {
    let root = folderbase();
    let receipt = attest_folderbase_root(root.path()).expect("root receipt");
    fs::create_dir_all(root.path().join(".folderbase/local")).expect("local state");
    fs::write(
        root.path().join(".folderbase/local/head.json"),
        serde_json::to_vec_pretty(&serde_json::json!({
            "format": "folderbase-local-head-v1",
            "folderbase_id": FOLDERBASE_ID,
            "root_instance_sha256": receipt.root_instance_sha256,
            "version_id": "fbversion_0198ee40-a111-7aaa-8000-000000000001",
            "version_sha256": "a".repeat(64)
        }))
        .expect("head JSON"),
    )
    .expect("local head");

    let plan = FolderbaseVersionStore::open(root.path())
        .expect("open")
        .plan_capture()
        .expect("plan with current local head");
    let head = plan.current_local_head().expect("observed head");
    assert_eq!(
        head.version_id(),
        "fbversion_0198ee40-a111-7aaa-8000-000000000001"
    );
    assert_eq!(head.version_sha256(), "a".repeat(64));
}

#[test]
fn capture_inventory_enforces_the_folderbase_version_entry_bound() {
    let root = folderbase();
    for index in 0..(MAX_CAPTURE_PLAN_RECORDS - 1) {
        fs::create_dir(root.path().join(format!("d{index:05}"))).expect("bounded directory");
    }

    assert!(matches!(
        FolderbaseVersionStore::open(root.path())
            .expect("open")
            .plan_capture(),
        Err(FolderbaseCaptureError::InventoryLimitExceeded {
            limit: CapturePlanLimitKind::Entries,
            maximum,
            ..
        }) if maximum == MAX_CAPTURE_PLAN_RECORDS as u64
    ));
}

#[cfg(unix)]
#[test]
fn hard_links_and_special_nodes_are_typed_exclusions_instead_of_silent_loss() {
    use std::{ffi::CString, os::unix::ffi::OsStrExt};

    let root = folderbase();
    fs::write(root.path().join("original.bin"), "same inode").expect("regular file");
    fs::hard_link(
        root.path().join("original.bin"),
        root.path().join("alias.bin"),
    )
    .expect("hard link");
    let fifo = root.path().join("events.fifo");
    let fifo_path = CString::new(fifo.as_os_str().as_bytes()).expect("FIFO path");
    assert_eq!(unsafe { libc::mkfifo(fifo_path.as_ptr(), 0o600) }, 0);

    let plan = FolderbaseVersionStore::open(root.path())
        .expect("open")
        .plan_capture()
        .expect("typed unsupported nodes");
    assert!(
        !plan
            .entries()
            .iter()
            .any(|entry| matches!(entry.path(), "original.bin" | "alias.bin" | "events.fifo"))
    );
    let observed = plan
        .exclusions()
        .iter()
        .map(|entry| (entry.path(), entry.kind(), entry.reason()))
        .collect::<Vec<_>>();
    assert_eq!(
        observed,
        vec![
            (
                "alias.bin",
                CaptureExclusionKind::HardLink,
                CaptureExclusionReason::UnsupportedV1,
            ),
            (
                "events.fifo",
                CaptureExclusionKind::Fifo,
                CaptureExclusionReason::UnsupportedV1,
            ),
            (
                "original.bin",
                CaptureExclusionKind::HardLink,
                CaptureExclusionReason::UnsupportedV1,
            ),
        ]
    );
}

#[cfg(unix)]
#[test]
fn symlink_metadata_preserves_a_safe_exact_target_and_rejects_escape() {
    use std::os::unix::fs::symlink;

    let root = folderbase();
    fs::create_dir_all(root.path().join("docs")).expect("docs");
    fs::write(root.path().join("docs/readme.md"), "opaque").expect("target");
    fs::create_dir(root.path().join("links")).expect("links");
    symlink("../docs/readme.md", root.path().join("links/readme")).expect("safe link");

    let plan = FolderbaseVersionStore::open(root.path())
        .expect("open")
        .plan_capture()
        .expect("safe link metadata");
    let link = plan
        .entries()
        .iter()
        .find(|entry| entry.path() == "links/readme")
        .expect("link entry");
    assert_eq!(link.kind(), CaptureEntryKind::Symlink);
    assert_eq!(link.symlink_target(), Some("../docs/readme.md"));

    symlink("../../outside", root.path().join("links/escape")).expect("unsafe link");
    assert!(matches!(
        FolderbaseVersionStore::open(root.path())
            .expect("reopen")
            .plan_capture(),
        Err(FolderbaseCaptureError::UnsafeSymlinkTarget(path))
            if path == Path::new("links/escape")
    ));
}

#[test]
fn in_scope_paths_fail_closed_when_the_portable_depth_limit_is_exceeded() {
    let root = folderbase();
    let too_deep = std::iter::repeat_n("d", 129).collect::<Vec<_>>().join("/");
    fs::create_dir_all(root.path().join(&too_deep)).expect("deep tree");

    assert!(matches!(
        FolderbaseVersionStore::open(root.path())
            .expect("open")
            .plan_capture(),
        Err(FolderbaseCaptureError::UnsafePortablePath(path))
            if path.components().count() == 129
    ));
}

#[cfg(target_os = "linux")]
#[test]
fn in_scope_paths_fail_closed_on_non_utf8_and_portable_case_collisions() {
    use std::{ffi::OsString, os::unix::ffi::OsStringExt};

    let non_utf8 = folderbase();
    fs::write(
        non_utf8
            .path()
            .join(OsString::from_vec(vec![0xff, b'.', b'b', b'i', b'n'])),
        "opaque",
    )
    .expect("non-UTF-8 path");
    assert!(matches!(
        FolderbaseVersionStore::open(non_utf8.path())
            .expect("open")
            .plan_capture(),
        Err(FolderbaseCaptureError::UnsafePortablePath(_))
    ));

    let collision = folderbase();
    fs::write(collision.path().join("Readme.md"), "one").expect("first case");
    fs::write(collision.path().join("README.md"), "two").expect("second case");
    assert!(matches!(
        FolderbaseVersionStore::open(collision.path())
            .expect("open")
            .plan_capture(),
        Err(FolderbaseCaptureError::PortablePathCollision { .. })
    ));
}

#[test]
fn required_ignore_marker_and_bounded_policy_fail_closed() {
    let missing = folderbase();
    fs::remove_file(missing.path().join(".folderbaseignore")).expect("remove marker");
    assert!(matches!(
        FolderbaseVersionStore::open(missing.path()),
        Err(FolderbaseCaptureError::RequiredMarker(path))
            if path.ends_with(".folderbaseignore")
    ));

    let oversized = folderbase();
    let policy = fs::File::options()
        .write(true)
        .open(oversized.path().join(".folderbaseignore"))
        .expect("policy");
    policy
        .set_len(folderbase_core::MAX_FOLDERBASEIGNORE_BYTES + 1)
        .expect("oversized policy");
    assert!(matches!(
        FolderbaseVersionStore::open(oversized.path())
            .expect("marker is present")
            .plan_capture(),
        Err(FolderbaseCaptureError::IgnorePolicyTooLarge { maximum_bytes })
            if maximum_bytes == folderbase_core::MAX_FOLDERBASEIGNORE_BYTES
    ));
}

#[test]
fn local_head_from_another_physical_root_is_rejected() {
    let source = folderbase();
    let destination = folderbase();
    let receipt = attest_folderbase_root(source.path()).expect("source root");
    fs::create_dir_all(destination.path().join(".folderbase/local")).expect("local state");
    fs::write(
        destination.path().join(".folderbase/local/head.json"),
        serde_json::to_vec(&serde_json::json!({
            "format": "folderbase-local-head-v1",
            "folderbase_id": FOLDERBASE_ID,
            "root_instance_sha256": receipt.root_instance_sha256,
            "version_id": "fbversion_0198ee40-a111-7aaa-8000-000000000001",
            "version_sha256": "b".repeat(64)
        }))
        .expect("head JSON"),
    )
    .expect("foreign head");

    assert!(matches!(
        FolderbaseVersionStore::open(destination.path()),
        Err(FolderbaseCaptureError::InvalidLocalHead(message))
            if message.contains("attested physical Folderbase Root")
    ));
}

fn state_paths(root: &Path) -> Vec<String> {
    let mut paths = walkdir::WalkDir::new(root.join(".folderbase"))
        .into_iter()
        .map(|entry| {
            entry
                .expect("state entry")
                .path()
                .strip_prefix(root)
                .expect("relative state")
                .to_string_lossy()
                .into_owned()
        })
        .collect::<Vec<_>>();
    paths.sort();
    paths
}
